package model;

// default package
// Generated 2017/3/22 下午 10:41:27 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;

/**
 * Oper generated by hbm2java
 */
/**
 * @author hungming
 *
 */
@Entity
@Table(name = "Oper", schema = "Nurse")
public class OperBean implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "oper_id", unique = true, nullable = false)

	private Integer operId;
	private String name;
	private Date updateTime;
	
	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
 
	 
 
	@Override
	public String toString() {
		return "OperBean [operId=" + operId + ", name=" + name + ", updateTime=" + updateTime + "]";
	}

	public OperBean() {
	}

	public OperBean(String name ,Date updateTime) {
		this.name = name;
		this.updateTime = updateTime;
	}

	

	public Integer getOperId() {
		return this.operId;
	}

	public void setOperId(Integer operId) {
		this.operId = operId;
	}

	@Column(name = "name", nullable = false, length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
